name: CI

on:
  push:
    branches: ['main']
#    paths-ignore:
#      - '.github/**'
#      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-18
    steps:
      - name: Download repo
        uses: actions/checkout@v3
      - name: List directory contents
        run: ls
      - name: Setup python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.9.8
      - name: Test requirements.txt file
        run: |
         pip install -r req.txt
         echo "All Packages"
         pip list
